# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x' # Replace with the .NET SDK version compatible with your project

- script: dotnet tool install dotnet-sonarscanner --tool-path ./.sonarscanner
  displayName: 'Install SonarScanner to Local Path'

# Begin SonarQube analysis using local tool path
- script: |
    dotnet sonarscanner begin /o:"observability-360" /k:"observability-360_productmvc" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="e9711f69cd2c0e4c30c36b935127ce0d4ab668b3"
  displayName: 'SonarQube Begin Analysis'
  env:
    SONAR_TOKEN: 'e9711f69cd2c0e4c30c36b935127ce0d4ab668b3'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: dotnet sonarscanner end /d:sonar.token="e9711f69cd2c0e4c30c36b935127ce0d4ab668b3"
  displayName: 'SonarQube End Analysis'
